sonar.projectKey=gc_kpi_analytics
sonar.projectName=gc_kpi_analytics
sonar.projectVersion=1.0

# Rutas de origen y pruebas
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=test_*.py
sonar.exclusions=venv/**,Dockerfile,requirements.txt

# Configuración de lenguaje
sonar.language=py
sonar.sourceEncoding=UTF-8

# Reporte de Cobertura generado por pytest-cov
sonar.python.coverage.reportPaths=coverage.xml