version: '3.8'

services:
  # Base de Datos Transaccional (Para GC_Auth, Ventas, Inventario, Finanzas)
  postgres-cordillera:
    image: postgres:15-alpine
    container_name: db-cordillera
    environment:
      POSTGRES_USER: cordillera_admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cordillera_db
    ports:
      - "5432:5432" # Expone el puerto para que Java se pueda conectar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # pgAdmin (Interfaz gráfica para ver tu base de datos en el navegador)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-cordillera
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cordillera.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres-cordillera
    restart: always

volumes:
  postgres_data: