services:
  postgres-db:
    image: postgres:15
    container_name: cordillera-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cordillera_db
      POSTGRES_USER: cordillera_admin
      POSTGRES_PASSWORD: admin123

  redis-cache:
    image: redis:7
    container_name: cordillera-redis
    ports:
      - "6379:6379"

  eureka-server:
    build: ./eureka_server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api_gateway
    ports:
      -  "9090:8080"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  gc-auth:
    build: ./gc_auth
    ports:
      - "8089:8081"
    depends_on:
      - eureka-server
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/cordillera_db
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  gc-ventas:
    build: ./gc_ventas
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/cordillera_db
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  gc-inventario-compras:
    build: ./gc_inventario_compras
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/cordillera_db
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  gc-finanzas:
    build: ./gc_finanzas
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/cordillera_db
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

gc-bff-reportes:
    build: ./gc_bff_reportes  # <--- Fíjate que no esté doble
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - redis-cache
    environment:
      REDIS_HOST: redis-cache
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
      # ---------------------------------------------------
  # INFRAESTRUCTURA PARA COMUNICACIÓN ASÍNCRONA Y KPIs
  # ---------------------------------------------------
rabbitmq:
    image: rabbitmq:3-management
    container_name: gc-rabbitmq
    ports:
      - "5672:5672"   # Puerto interno donde Java y Python se conectan
      - "15672:15672" # Panel visual en tu navegador (usuario: guest / pass: guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

mongodb:
    image: mongo:6.0
    container_name: gc-mongodb
    ports:
      - "27017:27017" # Puerto por defecto de MongoDB
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped