redis-cache:
    image: redis:7
    container_name: cordillera-redis
    ports:
      - "6379:6379"

  gc-bff-reportes:
    build: ./gc_bff_reportes
    
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - redis-cache
    environment:
      REDIS_HOST: redis-cache
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/