server:
  port: 8085

spring:
  application:
    name: GC-BFF-REPORTES
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  # 👇 AQUÍ ESTÁ EL CAMBIO: main debe ir justo dentro de spring
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      dashboardCB:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50