server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  # 1. CONEXIÓN A REDIS (Para el Rate Limiting)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  cloud:
    gateway:
      # 2. CONFIGURACIÓN DE TIMEOUTS (Global)
      httpclient:
        connect-timeout: 2000 # 2 segundos máximo para conectar
        response-timeout: 5s  # 5 segundos máximo esperando respuesta

      # 3. CONFIGURACIÓN DE CORS GLOBAL (Para el Frontend)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # En producción cambiar por ej: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      # 4. ENRUTAMIENTO DINÁMICO Y PROTECCIÓN
      routes:
        # A. SERVICIO DE AUTENTICACIÓN (Público, sin JWT, pero con Rate Limiting)
        - id: gc-auth
          uri: lb://GC-AUTH
          predicates:
            - Path=/api/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userIpKeyResolver}"

        # B. SERVICIO DE VENTAS (Protegido con JWT y Rate Limiting)
        - id: gc-ventas
          uri: lb://GC-VENTAS
          predicates:
            - Path=/api/ventas/**
          filters:
            - AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userIpKeyResolver}"

        # C. SERVICIO DE INVENTARIO Y COMPRAS
        - id: gc-inventario
          uri: lb://GC-INVENTARIO-COMPRAS
          predicates:
            - Path=/api/inventario/**
          filters:
            - AuthenticationFilter

        # D. SERVICIO DE FINANZAS
        - id: gc-finanzas
          uri: lb://GC-FINANZAS
          predicates:
            - Path=/api/finanzas/**
          filters:
            - AuthenticationFilter

        # E. SERVICIO BFF REPORTES
        - id: gc-bff-reportes
          uri: lb://GC-BFF-REPORTES
          predicates:
            - Path=/api/bff/**
          filters:
            - AuthenticationFilter

# 5. CONEXIÓN AL DISCOVERY SERVER (EUREKA)
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true