server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  
  # 1. Conexión a Redis (Lee la variable del docker-compose)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  cloud:
    gateway:
      routes:
        # Ejemplo con tu ruta de Ventas
        - id: gc-ventas
          uri: lb://GC-VENTAS # Carga balanceada desde Eureka
          predicates:
            - Path=/api/ventas/**
          filters:
            - AuthenticationFilter # Tu filtro JWT actual
            
            # 2. EL NUEVO ESCUDO DE RATE LIMITING
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10 # Peticiones permitidas por segundo
                redis-rate-limiter.burstCapacity: 20 # Ráfaga máxima permitida en un instante
                redis-rate-limiter.requestedTokens: 1 # Costo de cada petición
                key-resolver: "#{@userIpKeyResolver}" # Llama al Bean que creamos en el Paso 2