server:
  port: 8090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # En producción aquí pondrías la IP de tu frontend
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # RUTA ABIERTA: No necesita token para entrar a registrarse o loguearse
        - id: gc-auth-open
          uri: lb://GC-AUTH
          predicates:
            - Path=/auth/login, /auth/registro

        # RUTA PROTEGIDA: Cualquier otra cosa que empiece con /auth/ (ej: /auth/perfil)
        # requerirá pasar por nuestro "AuthenticationFilter"
        - id: gc-auth-protected
          uri: lb://GC-AUTH
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter # <-- Aquí se activa el escudo

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/