server:
  port: 8081 # El puerto que definiste en tu diagrama para Auth

spring:
  application:
    name: gc-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/cordillera_db
    username: cordillera_admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update # La magia: Spring creará las tablas SQL por nosotros
    show-sql: true # Para ver las consultas en la terminal

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: your-super-secret-key-change-this-in-production-min-32-chars
  expiration: 86400000