server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. RUTA PARA AUTENTICACIÓN (Login público, no usa el filtro)
        - id: auth-service
          uri: lb://GC-AUTH
          predicates:
            - Path=/api/auth/**

        # 2. RUTA PARA USUARIOS ADMIN (Protegida)
        - id: auth-admin-service
          uri: lb://GC-AUTH
          predicates:
            - Path=/api/admin/**
          filters:
            - AuthenticationFilter

        # 3. RUTA PARA VENTAS (Protegida)
        - id: ventas-service
          uri: lb://GC-VENTAS
          predicates:
            - Path=/ventas/**
          filters:
            - AuthenticationFilter

        # 4. RUTA PARA INVENTARIO/PRODUCTOS (Protegida)
        - id: inventario-service
          uri: lb://GC-INVENTARIO-COMPRAS
          predicates:
            - Path=/api/inventario/**
          filters:
            - AuthenticationFilter

        # 5. RUTA PARA REPORTES PDF (Protegida)
        - id: reportes-service
          uri: lb://GC-REPORTES-PDF
          predicates:
            - Path=/api/reportes/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
      
springdoc:
  swagger-ui:
    urls:
      - name: 01. Autenticación y Admin (gc-auth)
        url: /api/auth/v3/api-docs
      - name: 02. Ventas (gc-ventas)
        url: /ventas/v3/api-docs
      - name: 03. Inventario (gc-inventario-compras)
        url: /api/inventario/v3/api-docs
      - name: 04. Reportes PDF (gc_reportes_pdf)
        url: /api/reportes/v3/api-docs