server:
  port: 8084

spring:
  application:
    name: GC-FINANZAS
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cordillera_db}
    username: cordillera_admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # Apagado por seguridad: No queremos que los logs expongan las consultas SQL en producción
  jmx:
    enabled: false


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}