server:
  port: 8761 # El puerto estándar a nivel mundial para Eureka

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # Tú eres el servidor, no necesitas registrarte a ti mismo
    fetch-registry: false       # No busques a otros servidores Eureka