server:
  port: 8083

spring:
  application:
    name: GC-INVENTARIO-COMPRAS
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cordillera_db}
    username: cordillera_admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /api/inventario/v3/api-docs